version: '3'
services:
     web:
         build: .
         tty: true
         volumes:
             - .:/go/app
         ports:
             - "8081:8081"
     nginx:
         image: nginx:latest
         container_name: nginx
         ports:
             - "80:80"
             - "443:443"
         depends_on:
             - web
         # volumes:
             # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
             # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
             # HTTPS用の証明書とキーをホストOSから、ゲストOSに連結する
             # - /home/yukkuri/certificates/yukkuri.me.crt:/etc/nginx/conf.d/yukkuri.me.crt:Z
             # - /home/yukkuri/certificates/yukkuri.me.key:/etc/nginx/conf.d/yukkuri.me.key:Z
             # NGINXのWebアプリ（index.html等）をホストOSから、ゲストOSに連結する
             # - ./html:/usr/share/nginx/html
