version: '3'
services:
     web:
         container_name: web
         build: .
         tty: true
         volumes:
             - .:/go/app
         ports:
             - "8081:8081"
     nginx:
         image: nginx:latest
         container_name: nginx
         ports:
             - "80:80"
             - "443:443"
         depends_on:
             - web
         volumes:
             # mount NGINX config file
             - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
             # mount Let't Encrypt certification and private key
             # - /etc/letsencrypt/live/takechi-apps/cert.pem:/etc/letsencrypt/live/takechi-apps/cert.pem
             # - /etc/letsencrypt/live/takechi-apps/privkey.pem:/etc/letsencrypt/live/takechi-apps/privkey.pem
